development:
  adapter: postgresql
  encoding: unicode
  database: gamerfinder-development
  pool: 5
  port: 5432
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: gamerfinder-test
  pool: 5
  port: 5432
  host: localhost
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: gamerfinder-production
  pool: 5
  port: 5432
  host: localhost