development:
  adapter: postgresql
  encoding: unicode
  database: gamerfinder-development
  pool: 5
  port: 5432
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: gamerfinder-test
  pool: 5
  port: 5432
  host: localhost

